spring:
  data:
    mongodb:
      uri: mongodb://67.205.168.28:27017/meli

webDataFilter:
  toExcludePath: swagger-, api-docs, csrf, url-shorten, gateway

domain: http://localhost/
server:
  port: 80
